# Generated by Django 5.0.7 on 2024-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_fotografia_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
